token = 'MTAyMDQ4Mjg1MDY5MDE3MDk1MQ.GlfG7U.wRJLob-EWi8P3qzb-sSDelC_q6ZHV9_0S4kiL4'
bucket = ''
channel = ''

timer_delay = 20

#postgresql server config
host='localhost'
database='postgres'
user='postgres'
password='password'